### ISSUE TITLE
Line height

### ISSUE THREAD

**Issue by hend0298** [hend0298/just-your-type#3]
@thomasjbradley I used the line height in CSS to fix the spacing between the two sections of type but Markbot says I shouldn't use line height. Is there a class I can put on the html to change the line height?

**Comment by hend0298** [comment]
> @thomasjbradley I used to line height in CSS to fix the spacing between the two sections of type but Markbot says I shouldn't use line height. Is there a class I can put on the html to change the line height?

**Comment by thomasjbradley** [comment]
Hmm... that’s an interesting conundrum. I don’t think there is a solution. Does it look completely horrible with the default `line-height`?

**Comment by hend0298** [comment]
@thomasjbradley There is a space but it's not terrible. Should I just leave it with the default the line height?

**Comment by thomasjbradley** [comment]
Yeah, just leave it.
